stages:
    - 🩻 scan
    - 🔬 observe
    - 🚀 deploy

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: "clone"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - node_modules/

mkdocs:
  trigger:
    project: brie/mkdocstil

update TIL.brie.dev:
  stage: 🚀 deploy
  image: node:19-slim
  environment: 
    name: staging/TIL.db
    url: https://s3.amazonaws.com/til.brie.dev/tils.db
  artifacts:
    paths:
      - tils.db
  script:
      - apt-get update && apt-get install curl git python3 python3-pip python3-venv unzip wget -y
      - npm i -g vercel 
      - python3 -m pip install --upgrade pip
      -  pip install -r requirements.txt
      # - curl --fail -o tils.db https://s3.us-east-2.amazonaws.com/til.brie.dev/tils.db
      - python3 build_database.py # This is our goal. 
      - datasette . --get /  | grep "Carranza"
      - python3 update_readme.py --rewrite
      - ln -s /usr/bin/python3 /usr/local/bin/python
      - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - ls -ahls "awscli-bundle.zip"
      - unzip "awscli-bundle.zip"
      -  ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - /usr/local/bin/aws --version
      - /usr/local/bin/aws configure set region us-east-2
      - /usr/local/bin/aws s3 cp tils.db s3://$S3_BUCKET/tils.db
      - /usr/local/bin/aws s3 ls s3://$S3_BUCKET/tils.db
      - wget -S  --quiet  https://latest.datasette.io/fixtures.db
      - datasette publish vercel tils.db fixtures.db  --token $NOW_TOKEN         --project til        --scope briecarranza-gmailcom        --metadata metadata.yaml         --static static:static         --install datasette-template-sql         --install "datasette-sitemap>=1.0"      --install "datasette-atom>=0.7"      --install datasette-json-html         --install beautifulsoup4         --install "datasette-debug-asgi>=1.1"        --install "datasette-graphql>=0.12"      --install datasette-media         --install datasette-block-robots          --plugins-dir plugins        --template-dir templates          --public
      - git status
      - git config --global user.email "bcarranza@gitlab.com"
      - git config --global user.name "Brie Carranza"
      - ./commit.sh
      #- git commit -m "🤖 Beep boop: Updated README for commit $CI_COMMIT_SHORT_SHA [skip ci]" README.md  ||  echo "No changes, nothing to commit!"
      - git remote rm origin && git remote add origin https://brie:${TIL_TOKEN}@gitlab.com/$CI_PROJECT_PATH.git
      #- git push -o ci.skip  origin main # HEAD:$CI_COMMIT_REF_NAME # Pushes to the same branch as the trigger

---

include:
   - template: Verify/Browser-Performance.gitlab-ci.yml
   - template: Code-Quality.gitlab-ci.yml
   - template: Jobs/Dependency-Scanning.gitlab-ci.yml

browser_performance:
  stage: 🔬 observe
  variables:
    URL: https://til.brie.dev 
  artifacts:
    paths:
      - sitespeed-results/
      - performance.json
    reports:
      performance: performance.json

pages:
  stage: 🚀 deploy 
  needs: ["browser_performance"]
  script:
    - mv sitespeed-results public
  artifacts:
    paths:
      - public/

